name: Environment Variable Configuration

on:
  push:
    branches:
      - master
      - prod

jobs:
  configure-environment:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:

    - name: Display Environment Variables
      run: |
        echo "Environment variable value: $environment"
